services:
  - type: web
    name: telegram-music-player-server
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install && npm run build && cd ../web && npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 22.10.0
      - key: PORT
        value: 10000
      - key: BOT_TOKEN
        sync: false
      - key: MINI_APP_URL
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
